# Generated by Django 2.2.1 on 2019-07-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='nick',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
